# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  amazon_associate_tag: <%= ENV["AMAZON_ASSOCIATE_TAG"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_key: <%= ENV["AWS_SECRET_KEY"] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

development:
  <<: *defaults
  secret_key_base: 6353871fc4c0b193a1d3739a0fade93d0d9d3b7b308dc1424d038b36a1f7d452c44bfc987594df2466ee5af5839536162aca86ce7ed1126ad279f3c3219d3695

test:
  <<: *defaults
  secret_key_base: 533ef74e69841ceada449a33acbb51ddf3011ca7fc6b1d7ac2cf27c5a0230d251d90c87f1624e8c3dca095ccda76db1d992d03f53247c081ab7341e0aa172175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
